### ISSUE TITLE
Hedgehog support?

### ISSUE THREAD

**Issue by shinzui** [brandonchinn178/skeletest#29]
Do you plan to support `Hedgehog`? `Skeletest` looks great, but migrating from `tasty` without `Hedgehog` support would be challenging. We heavily use `Hedgehog`, especially its state-based testing, which was difficult to implement. My main interest in `Skeletest`, though I haven't tried it yet, is its better snapshot rendering support since `tasty-golden` is limited in that regard.

**Comment by brandonchinn178** [comment]
Take a look at `Skeletest.Prop.Gen` 🙂

**Comment by shinzui** [comment]
I missed that. Thanks.
